[package]
name = "vistream"
version = "0.1.0"
edition = "2021"

[dependencies]
libcamera = "0.2.3"
ndarray = "0.16.1"
tungstenite = { version = "0.24.0", optional = true }
turbojpeg = "1.1.1"
wgpu = "22.1.0"

[features]
web = ["dep:tungstenite"]

