[package]
name = "vistream-camera-server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
libcamera = "0.3.0"
vistream-protocol = { version = "0.1.0", path = "../protocol" }
