[package]
name = "vistream-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.3.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_repr = "0.1.19"
thiserror = "2.0.3"
